# Generated by Django 4.1.3 on 2022-11-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
