# Generated by Django 4.1.3 on 2022-11-25 15:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default="profile/default.jpeg",
                force_format="JPEG",
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[128, 128],
                upload_to="profile",
            ),
        ),
    ]
