# Generated by Django 4.1.3 on 2022-11-22 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_profile_img_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
